CC := gcc
TSTD := tests
BLDD := build
BIND := bin
INCD := include
LIBD := lib

EXEC := discordinit
TEST_EXEC := $(EXEC)_tests

MAIN := $(BLDD)/main.o

# ALL_SRCF :=
# ALL_OBJF :=
# ALL_FUNCF :=

TEST_ALL_SRCF := $(shell find $(TSTD) -type f -name *.c)
TEST_SRCF := $(filter-out $(TEST_REF_SRCF), $(TEST_ALL_SRCF))

INC := -I $(INCD) -I $(LIBD)

CFLAGS := -Wall -Werror -Wno-unused-variable -Wno-unused-function -MMD -fcommon
COLORF := -DCOLOR
DFLAGS := -g -DDEBUG -DCOLOR
PRINT_STAMENTS := -DERROR -DSUCCESS -DWARN -DINFO

STD := -std=gnu11
TEST_LIB := -L/usr/local/lib -lcriterion
LIBS := $(LIB)

CFLAGS += $(STD)

.PHONY: clean all setup debug

all: setup $(BIND)/$(TEST_EXEC)

debug: CFLAGS += $(DFLAGS) $(PRINT_STAMENTS) $(COLORF)
debug: all

setup: $(BIND) $(BLDD)
$(BIND):
	mkdir -p $(BIND)
$(BLDD):
	mkdir -p $(BLDD)

$(BIND)/$(EXEC): $(MAIN) $(ALL_FUNCF)
	$(CC) $(MAIN) $(ALL_FUNCF) -o $@ $(LIBS)

$(BIND)/$(TEST_EXEC): $(TEST_SRCF)
	$(CC) $(CFLAGS) $(INC) $(TEST_SRCF) $(TEST_LIB) $(LIBS) -o $@

$(BLDD)/%.o: $(SRCD)/%.c
	$(CC) $(CFLAGS) $(INC) -c -o $@ $<

$(LIBD)/%.o: $(LIBD)/%.c
	$(CC) $(CFLAGS) $(INC) -c -o $@ $<
	strip --strip-unneeded $@

clean:
	rm -rf $(BLDD) $(BIND) $(LIB)

.PRECIOUS: $(BLDD)/*.d
-include $(BLDD)/*.d
