name: Blackbox Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Test_Cases:
    name: Run Test Cases
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get -y install build-essential

    - name: Download and install criterion
      run: sudo apt-get install libcriterion-dev

    - name: Create C main to Compile
      run: |
        echo "#include <stdio.h>" > src/main.c
        echo "int main() { printf(\"Hello World\"); }" >> src/main.c
        cat src/main.c

    - name: Clean bin and make
      run: make -f MakeFile clean all -C . && echo "build done"

    - name: Set Test Environment Vars
      run: |
        echo "HOMEDIR=../" >> .env 
        echo "TOKEN=token" >> .env
        cat .env

    - name: Compile Rust Program
      run: cargo build

    - name: Run Test Cases
      run: |
        ls test_output
        bin/discordinit_tests -S --verbose=0 --timeout 30

