name: Blackbox Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build_and_Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get -y install build-essential

    - name: Download and install criterion
      run: sudo apt-get install libcriterion-dev

    - name: Clean bin and make
      run: make clean all -C . && echo "build done"
  
    - name: Run Test Cases
      run: bin/discordinit_tests -S --verbose=0 --timeout 30

